services:
  cache:
    image: redis:7-alpine
    restart: always
    expose:
      - 6380
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    networks:
      - tg_bot_network
  db:
    image: postgres:13
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - tg_bot_network

  yoga_bot_server:
    depends_on:
      - db
      - cache
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tg_bot_network
    volumes:
      - ./alembic/versions:/app/alembic/versions
    command: >
      bash -c "alembic revision --autogenerate -m \"check db\" 
      && alembic upgrade head 
      && python bot.py"
  backend:
    depends_on:
      - db
      - cache
      - yoga_bot_server
    ports:
      - "8001:8001"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tg_bot_network
    volumes:
      - ./alembic/versions:/app/alembic/versions
      - media:/app/app/media
    command:
      uvicorn app.main:app --host 0.0.0.0 --port 8001

volumes:
  app-db-data:
    driver: local
  cache:
    driver: local
  media:
    driver: local

networks:
  tg_bot_network:
    driver: bridge
